_target_: parco.models.rl.PARCORLModule

# NOTE: this should be done on the model side
metrics:
  train: ["loss", "reward", "halting_ratio", "pos_ratio"]
  val: ["reward", "halting_ratio", "pos_ratio"]
  test: ["reward", "halting_ratio", "pos_ratio"]
  log_on_step: True